### ISSUE TITLE
Loading wrong image files on mac/linux

### ISSUE THREAD

**Issue by EvaKroon** [diku-dk/DIKUArcade#28]
In SpaceTaxi, when loading image files from the Assets\Images directory, some (but not all) are loaded incorrectly, displaying a wrong image in the window. 
It seems like the files being incorrectly loaded differs from computer to computer.

**Comment by alexpanter** [comment]
You need to explain exactly what the problem is - did you get an error message? What images did not load correctly? How do they display? Something that makes it possible to reproduce your error or at least trying to find out, what is going wrong.

And it would be great to know, what operating systems are implied with "from computer to computer".

**Comment by EvaKroon** [comment]
There are no error messages, and apart from the wrong loading of images, the game runs as intended. 
For our group, white corner images and white half-circles were loaded incorrectly, but I have heard from other groups, that they had issues with fx. the green corner images. It appears to be somewhat random which images are placed in stead of the images with issues. 
From computer to computer implies computers with the operating systems mac and linux, as titled. There is to my knowledge currently no apparent issue on computers running the windows operating system. 


I have attached an image of short-n-sweet when displayed on my computer, which runs Mac OSX Sierra

![skaermbillede 2018-05-08 kl 14 35 15](https://user-images.githubusercontent.com/32454661/39757438-1ea453f8-52cd-11e8-8978-c7120bb5d1e0.png)

**Comment by BorisDuedder** [comment]
What is the machine configuration? Maybe the graphics card RAM is not big enough to store all pictures, because we use textures for the images in the game. 
@alexpanter The OpenGL error status should be changed after loading the texture.

**Comment by alexpanter** [comment]
@BorisDuedder That seems weird, because I have observed exactly the same issue with a completely new Mac computer - which means, no matter if CPU or GPU is used, there should be enough texture memory.
Besides, the largest image is < 10Kb on disk.
I will look into how to use OpenGL error status.

**Comment by sortraev** [comment]
I noticed two things: 
- the problem only pertains to images containing pixels with alpha channels != 255 (ie. non-square images)
- the problem only occurs on non-windows systems

So I figured this problem might have something to do with OpenTK handling transparency in textures on non-windows systems. I opened "ironstone-upper-left.png" in Pinta (an mspaint-like app for linux) and resaved it under the same name. The texture would now draw properly when running my game.

So my best guess is that the png files must have originally been compressed on a windows machine using a codec that produced alpha channel metadata unreadable by non-windows systems. I have only tested it on a single png file (the one mentioned above) and on my own pc, so if anyone's willing to go through the entirety of Assets_v2.zip and re-exporting every single png file, this *might* be an effective solution

**Comment by sortraev** [comment]
Update:
I decided to re-export each png image using Pinta. Short-n-sweet.txt and the-beach.txt now both draw as intended on my pc running linux. Will people running linux and mac please download the attached Assets_v2.1.zip and test for themselves? 

[Assets_v2.1.zip](https://github.com/diku-dk/DIKUArcade/files/1988911/Assets_v2.1.zip)

**Comment by alexpanter** [comment]
@sortraev You are right - this fixes the problem! I will post this on absalon as well as attach this zip folder. Thank you for your help :)

**Comment by alexpanter** [comment]
I will consider this issue closed. If someone still experiences problems after using the new images from @sortraev , then please reopen this issue.

**Comment by Ulrik-dk** [comment]
@alexpanter I am unsure as to whether the shaking of the taxi under acceleration is a feature or a bug. Due to unequal amounds if free space behind each taxisprite, the imagestrideprocess makes some wierd cuts. This issue persists through the codec chance, since it is an issue with image dimensions.

To illustrate the issue, i have these two examples:

1. Using the images from sortraev: https://vimeo.com/268948957
2. Using some changes to dimensions (based on sortraev's changed files): https://vimeo.com/268948954

If this is deemed a bug, and not a feature, ill gladly upload the zip with the new taxi sprites. I just want to avoid any semblance of plagiarism, in case the taxi is supposed to shake when it accelerates, as that is a plausible explaination.
